class_name SpriteAtlas
extends RefCounted
## Looks up sprites in the 0x72 atlas by name using data/atlas.json (generated by tools/gen_atlas.py).
## Animated sprites have their frames laid out left to right, each entry.w pixels apart.

const TEXTURE := preload("res://assets/dungeon_tileset_ii/atlas.png")
const JSON_PATH := "res://data/atlas.json"
const TILE := 16

static var _entries: Dictionary = {}


static func entries() -> Dictionary:
	if _entries.is_empty():
		var text := FileAccess.get_file_as_string(JSON_PATH)
		assert(text != "", "SpriteAtlas: cannot read " + JSON_PATH + " (run tools/gen_atlas.py)")
		_entries = JSON.parse_string(text)
	return _entries


static func has(name: String) -> bool:
	return entries().has(name)


static func entry(name: String) -> Dictionary:
	assert(has(name), "SpriteAtlas: no sprite named '" + name + "'")
	return entries()[name]


## Pixel region of one frame of a named sprite.
static func region(name: String, frame: int = 0) -> Rect2:
	var e := entry(name)
	return Rect2(e.x + frame * e.w, e.y, e.w, e.h)


static func frame_count(name: String) -> int:
	return int(entry(name).frames)


## Grid coordinates of a 16x16 tile, for TileSetAtlasSource.
static func tile_coords(name: String) -> Vector2i:
	var e := entry(name)
	assert(int(e.w) == TILE and int(e.h) == TILE, "SpriteAtlas: '" + name + "' is not a 16x16 tile")
	return Vector2i(int(e.x) / TILE, int(e.y) / TILE)


static func texture(name: String, frame: int = 0) -> AtlasTexture:
	var tex := AtlasTexture.new()
	tex.atlas = TEXTURE
	tex.region = region(name, frame)
	return tex


## Builds SpriteFrames from {animation_name: sprite_name}. Every animation loops at fps.
static func frames(animations: Dictionary, fps: float = 8.0) -> SpriteFrames:
	var sprite_frames := SpriteFrames.new()
	sprite_frames.remove_animation("default")
	for anim_name in animations:
		var sprite_name: String = animations[anim_name]
		sprite_frames.add_animation(anim_name)
		sprite_frames.set_animation_speed(anim_name, fps)
		sprite_frames.set_animation_loop(anim_name, true)
		for i in frame_count(sprite_name):
			sprite_frames.add_frame(anim_name, texture(sprite_name, i))
	return sprite_frames
